### ISSUE TITLE
Failed to activate the ever-notedown package

### ISSUE THREAD

**Issue by zeronosu77108** [cs150bf/ever-notedown#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.7
### Stack Trace

Failed to activate the ever-notedown package

```
At EEXIST: file already exists, mkdir '/Users/e145755/.atom/evnd'

Error: EEXIST: file already exists, mkdir '/Users/e145755/.atom/evnd'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:791:18)
    at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:343:23)
    at atom.confirm.buttons.Confirm (/Users/e145755/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1120:18)
    at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:767:49)
    at Object.module.exports.initGitDir (/Users/e145755/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1112:19)
    at Object.module.exports.initJSONFile (/Users/e145755/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1137:19)
    at Object.module.exports.loadJSON (/Users/e145755/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1173:21)
    at Object.module.exports.activate (/Users/e145755/.atom/packages/ever-notedown/lib/ever-notedown.coffee:332:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-runner, v2.4.1
ever-notedown, v0.2.7
japanese-wrap, v0.2.10
language-latex, v0.6.1
minimap, v4.12.1

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
Did you see the error after clicking on the "Confirm" button when asked "Will create directory at `path/to/your/directory`"?

Do you have a file or directory at `/Users/e145755/.atom/evnd`? This error seems strange to me, because if a directory already exists, it should not attempt to create a new directory there. But if there is a file (not a directory)... then I don't know. Maybe I should check for that case. But until then, could you check what you have at `/Users/e145755/.atom/evnd` and maybe rename/move it?
