### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: e1c40eb782cd94ba30e58e0d766626d4]' of null

### ISSUE THREAD

**Issue by th-m** [cs150bf/ever-notedown#104]
[Enter steps to reproduce:]

A. Either try to save a new note
or
B. Import a note from evernote....

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package 0.2.27

### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: e1c40eb782cd94ba30e58e0d766626d4]' of null

```
At /Users/thom/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: e1c40eb782cd94ba30e58e0d766626d4]' of null
    at NoteIndex.addnote (/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at Object.saveNewNote (/packages/ever-notedown/lib/ever-notedown.coffee:1384:34)
    at /packages/ever-notedown/lib/ever-notedown.coffee:1332:12)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  6x -3:35 core:move-down (input.hidden-input)
     -3:32.1.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -3:29.8.0 editor:toggle-line-comments (input.hidden-input)
     -2:24.4.0 core:move-up (input.hidden-input)
     -2:23.9.0 editor:newline (input.hidden-input)
     -2:23.4.0 core:paste (input.hidden-input)
     -2:16.4.0 core:backspace (input.hidden-input)
     -2:08.1.0 editor:move-to-first-character-of-line (input.hidden-input)
     -2:07.9.0 editor:newline (input.hidden-input)
     -2:02.9.0 core:move-down (input.hidden-input)
     -2:02.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -2:02.0 editor:newline (input.hidden-input)
     -2:01.0 core:backspace (input.hidden-input)
     -0:38.3.0 ever-notedown:toggle-note-list (input.hidden-input)
  5x -0:28.5.0 core:backspace (input.hidden-input)
     -0:24.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-hg 2.0.14 
atomic-chrome 0.3.3 
busy-signal 1.4.3 
compare-files 0.8.1 
ever-notedown 0.2.27 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
language-arm 1.2.2 
language-pug 0.0.21 
language-pug-jade 0.2.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-gcc 0.7.1 
linter-php 1.5.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
monokai-seti 0.9.0 
react 0.16.3 
save-commands 0.6.11 
seti-ui 1.9.0 
split-diff 1.5.1 
todo-show 2.1.0 
```

**Comment by th-m** [comment]
I was able to resolve this by uninstalling the package and deleting the `~/.atom/evnd` folder, and then reinstalling everything.
