### ISSUE TITLE
Uncaught Error: The index is locked. This might be due to a concurrent or crashed process

### ISSUE THREAD

**Issue by mirceamironenco** [cs150bf/ever-notedown#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.4
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.11
### Stack Trace

Uncaught Error: The index is locked. This might be due to a concurrent or crashed process

```
At /Users/MironencoMircea/.atom/packages/ever-notedown/lib/storage-manager.coffee:294

Error: The index is locked. This might be due to a concurrent or crashed process
    at Error (native)
    at Function.exports.StorageManager.StorageManager.addAppleScripts (/Users/MironencoMircea/.atom/packages/ever-notedown/lib/storage-manager.coffee:294:18)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/MironencoMircea/.atom/packages/ever-notedown/lib/storage-manager.coffee:448:36)
    at /Users/MironencoMircea/.atom/packages/ever-notedown/lib/evernote-helper.coffee:786:52
    at /Users/MironencoMircea/.atom/packages/ever-notedown/lib/evernote-helper.coffee:999:20
    at ChildProcess.exithandler (child_process.js:720:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:997:16)
    at Socket.<anonymous> (child_process.js:1166:11)
```
### Commands

```
     -0:48.8.0 ever-notedown:import-note-from-evernote (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:44.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "ever-notedown": {
    "liveUpdate": false
  }
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.11

# Dev
No dev packages
```

**Comment by abruneau** [comment]
Hello,
I have this bug. Do you know how I can solve it ?
Thanks

**Comment by sherlockkenan** [comment]
I  also get the problem ,do you know how to slove it?
thanks
