### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '#-' is not a valid sele...

### ISSUE THREAD

**Issue by coderbiq** [cs150bf/ever-notedown#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.11
### Stack Trace

Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '#-' is not a valid selector.

```
At /Users/macbookair/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:674

Error: Failed to execute 'querySelectorAll' on 'Element': '#-' is not a valid selector.
  at Error (native)
  at EVNDPreviewView.module.exports.EVNDPreviewView.scrollToRow (/Users/macbookair/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:674:21)
  at EVNDPreviewView.scrollToRow (/Users/macbookair/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:25:1)
  at /Users/macbookair/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:221:8
  at /Users/macbookair/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:236:9
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:120:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:478:22)
  at TextEditor.module.exports.TextEditor.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2871:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1063:20)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseWheel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:512:24)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "ever-notedown": {}
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
docblockr, v0.7.3
docs-snippets, v0.8.0
ever-notedown, v0.2.11
japanese-wrap, v0.2.7
project-manager, v2.6.1
terminal-panel, v1.14.1
vim-mode, v0.61.0
vim-mode-visual-block, v0.2.13

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
Version 0.2.16 should have this problem fixed so I'll close this issue for now. Please let me know if it's still present.
