### ISSUE TITLE
Uncaught TypeError: Cannot read property 'absPath' of undefined

### ISSUE THREAD

**Issue by yxsu** [cs150bf/ever-notedown#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.2
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'absPath' of undefined

```
At /Users/suyuxin/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1366

TypeError: Cannot read property 'absPath' of undefined
  at Object.module.exports.openNote (/Users/suyuxin/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1366:19)
  at Object.module.exports.file2Evernote (/Users/suyuxin/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1128:8)
  at /Users/suyuxin/.atom/packages/ever-notedown/lib/ever-notedown.coffee:475:12
  at Emitter.module.exports.Emitter.emit (/Users/suyuxin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at HTMLButtonElement.<anonymous> (/Users/suyuxin/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:452:22)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/suyuxin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Users/suyuxin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -4:09.3.0 ever-notedown:toggle (atom-text-editor.editor.is-focused)
  5x -3:43.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:41.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:28.8.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -1:25 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:16 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:12.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:47.7.0 ever-notedown:view-mathjax-macros (atom-text-editor.editor.is-focused)
     -0:44.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:33.7.0 ever-notedown:toggle-preview (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.0

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
@yxsu I hope the new versions (0.2.1, 0.2.2) fixed this problem. Let me know if you are still having problems.

PS. I suppose it's a bit quirky... since EVND tries to manage notes within a designated EVND folder, if you create a markdown file outside of that folder and then do "file2Evernote", EVND will first copy the file into the EVND folder before sending it to Evernote.

**Comment by cs150bf** [comment]
@yxsu I'll close this issue for now, please let me know if you're still seeing the error.
