### ISSUE TITLE
Failed to load the ever-notedown package

### ISSUE THREAD

**Issue by askg7dawn** [cs150bf/ever-notedown#22]
I tried to install this `ever-notedown` with using Atom UI but apm error occured.
Then I downloaded the `ever-notedown` from the author's repository as a zip file.
I expanded the zip file and put the `ever-notedown-master` folder into ~/.atom/packages/ directory after renaming it `ever-notedown`.
Then I started the Atom but the ever-notedown didn't work.
What should I do to use it?

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.12
### Stack Trace

Failed to load the ever-notedown package

```
At Cannot find module 'pathwatcher'

Error: Cannot find module 'pathwatcher'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/myUSERNAME/.atom/packages/ever-notedown/lib/ever-notedown.coffee:28:21)
  at Object.<anonymous> (/Users/myUSERNAME/.atom/packages/ever-notedown/lib/ever-notedown.coffee:25:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:363:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete-plus-python-jedi"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ],
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
AtomicChar, v0.3.9
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.3
ever-notedown, v0.2.12
file-icons, v1.6.11
haskell-ghc-mod, v1.1.2
haskell-pointfree, v0.1.2
ide-haskell-cabal, v1.0.0
japanese-menu, v1.5.0
japanese-wrap, v0.2.10
language-haskell, v1.5.0
language-latex, v0.6.1
language-matlab, v0.1.1
latex, v0.28.2
latexer, v0.2.7
minimap, v4.16.0
minimap-autohide, v0.10.1
minimap-hide, v0.3.0
project-manager, v2.6.5
script-runner, v1.8.4
symbols-tree-view, v0.10.1
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
Sorry for the delay in replying. Are you still having problems installing this package using the Atom UI? 

Downloading and unzipping the repository doesn't quite equate to "installing"... You probably need to 
1. `cd ~/.atom/packages/ever-notedown/`
2. `apm install`

Alternatively, you can try running `apm install ever-notedown` in command line, which should be equivalent to installing the package in the Atom UI. 

P.S. Have you taken a look at the [package documentation](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f) by any chance? The `installation` section, in particular, as there are a few things that you'll need to do before installing -- nothing too complicated, just creating a dedicated directory/git repo, really.

**Comment by askg7dawn** [comment]
Thank you for your answer. I still have a problem with it.
I tried `apm install` but some `npm error` and `gyp error` have occurred.
The error message said

```
npm ERR!  Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR!  This is most likely a problem with the runas package,
npm ERR!  not with npm itself.
npm ERR!  Tell the author that this fails on your system:
npm ERR!      node-gyp rebuild
npm ERR!  You can get their info via:
npm ERR!      npm owner ls runas
npm ERR!  There is likely additional logging output above.
```

so i will try to manage this problem first.
Thanks a lot.

**Comment by cs150bf** [comment]
@askg7dawn Have you updated the repo (`git pull` or re-download the repo) before running `apm install`? There were recent updates made to the package intended to resolve the `npm error` specifically. You might also want to do an `apm clean` before `apm install`.

**Comment by 7Moses** [comment]
@cs150bf Would love to get this working, as on now,

User@UserUser ~/.atom/packages/ever-notedown $ apm-beta install                [2.2.2]
Installing modules ✗

> git-utils@4.1.2 install /Users/User/.atom/packages/ever-notedown/node_modules/git-utils
> node-gyp rebuild

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
make: **\* No rule to make target `../../../../../../../../Applications/Atom', needed by`Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/User/.atom/packages/ever-notedown/node_modules/git-utils
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/User/.atom/.apm/.apmrc" "--userconfig" "/Users/User/.atom/.apmrc" "install" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/User/.atom/packages/ever-notedown/npm-debug.log
User@UserUser ~/.atom/packages/ever-notedown $

Ever-notedown is great work, wish I could contribute but way behind on the learning curve. 

Best,

**Comment by cs150bf** [comment]
@7Moses Just to make sure, have you tried running `apm clean` in the directory before the install?

**Comment by 7Moses** [comment]
@cs150bf, Thank you for replying. Yes, I ran apm clean, followed by apm install,

Best,

**Comment by 7Moses** [comment]
@cs150bf,

With ever-notedown 0.2.18, I am getting the alert: Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

I am using 1.6.0-beta8,

Best,

**Comment by cs150bf** [comment]
@7Moses I'm sorry to hear that... What about `apm rebuild`? Or if that fails, could you please try first enter the directory `ever-notedown/node_modules` and run `npm uninstall git-utils`, and then `cd ..` and run `apm install` again?

**Comment by 7Moses** [comment]
@cs150bf,

Thanks for replying. Used the sequence you described still getting:

"This is most likely a problem with the git-utils package,"

 I also tried here, https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp, got the error:  node-gyp@3.3.1  invalid; will continue reading, 

The sequence:

moses@MosesMoses ~/.atom/packages/ever-notedown $ cd /Users/moses/.atom/packages/ever-notedown/node_modules
moses@MosesMoses ~/.atom/packages/ever-notedown/node_modules $ npm uninstall git-utils
- git-utils@4.1.2 node_modules/git-utils
- nan@2.2.0 node_modules/nan
  moses@MosesMoses ~/.atom/packages/ever-notedown/node_modules $ cd ..              [2.2.2]
  moses@MosesMoses ~/.atom/packages/ever-notedown $ apm-beta install                [2.2.2]
  Installing modules ✗
  > git-utils@4.1.2 install /Users/moses/.atom/packages/ever-notedown/node_modules/git-utils
  > node-gyp rebuild

make: **\* No rule to make target `../../../../../../../../Applications/Atom', needed by`Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/moses/.atom/packages/ever-notedown/node_modules/git-utils
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/moses/.atom/.apm/.apmrc" "--userconfig" "/Users/moses/.atom/.apmrc" "install" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/moses/.atom/packages/ever-notedown/npm-debug.log
moses@MosesMoses ~/.atom/packages/ever-notedown $

**Comment by 7Moses** [comment]
@cs150bf,

I should have mentioned this, https://github.com/atom/git-utils/issues/69, "Failed at the git-utils@4.1.2 install script 'node-gyp rebuild" is also being reported by others,

Best,

**Comment by 7Moses** [comment]
I Updated to the latest atom-beta, and then did this, https://github.com/cs150bf/ever-notedown/issues/54, Works like a charm,
Thanks,
Best,

**Comment by ag14spirit** [comment]
@cs150bf,

Thanks for the hard work on developing this Atom Package! In my experience as a relatively inexperienced developer, I found that simply installing/updating the **[Xcode Command Line Tools](http://railsapps.github.io/xcode-command-line-tools.html)** was sufficient to eliminate all `npm` and `node-gyp rebuild` type errors from my install.

It may help you to minimize questions from n00bs like myself if you comment the Atom Package version number and reference it directly in the repository README.md file near the top under an "Install" heading.

Regards,
