### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getStyleElements' of undefined

### ISSUE THREAD

**Issue by willzhqiang** [cs150bf/ever-notedown#26]
Steps to reproduce the errors:
1. Import a note from evernote
2. Edit the note, then save it to evernote
3. Click the confirm button

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.14
### Stack Trace

Uncaught TypeError: Cannot read property 'getStyleElements' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/styles-element.js:81

TypeError: Cannot read property 'getStyleElements' of undefined
    at atom-styles.StylesElement.contextChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/styles-element.js:81:32)
    at atom-styles.StylesElement.attributeChangedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/styles-element.js:56:21)
    at EVNDPreviewView.module.exports.EVNDPreviewView.getTextEditorStyles (/Users/Qiang/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:523:22)
    at EVNDPreviewView.module.exports.EVNDPreviewView.getMarkdownPreviewCSS (/Users/Qiang/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:544:16)
    at ConfirmDialog.module.exports.ConfirmDialog.confirmChange (/Users/Qiang/.atom/packages/ever-notedown/lib/confirm-dialog.coffee:74:27)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -1:22.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:10.7.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "ever-notedown": {
    "sortBy": "default",
    "syntaxTheme": "One Light",
    "breakOnSingleNewline": true,
    "openNoteInEvernoteAuto": true
  }
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.14

# Dev
No dev packages
```

**Comment by Bryanprz** [comment]
Pinging. Same bug happening to me.

**Comment by iures** [comment]
Woops, looks like this is still an issue...

**Comment by amponce** [comment]
Was this ever resolved? I'm still getting a similar error:
`Uncaught TypeError: Cannot read property 'getStyleElements' of undefined
/Applications/Atom.app/Contents/Resources/app.asar/src/styles-element.js:74
Show Stack Trace
The error was thrown from the ever-notedown package. This issue has already been reported.`
