### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by hackervera** [cs150bf/ever-notedown#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.2
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/tyler/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1105

TypeError: undefined is not a function
  at Object.module.exports.file2Evernote (/Users/tyler/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1105:19)
  at /Users/tyler/.atom/packages/ever-notedown/lib/ever-notedown.coffee:475:12
  at Emitter.module.exports.Emitter.emit (/Users/tyler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at HTMLButtonElement.<anonymous> (/Users/tyler/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:452:22)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/tyler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Users/tyler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
  6x -2:04.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:02.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:02.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:01.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:19.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:19.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:16.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:15.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:01.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:01.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:41.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:40.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:38.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:22 ever-notedown:toggle (atom-text-editor.editor.is-focused)
     -0:18.4.0 core:paste (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "wrap-guide"
    ]
  },
  "ever-notedown": {
    "openNoteInEvernoteAuto": true
  }
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.2
multi-wrap-guide, v0.20.0

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
@tjgillies I released a very basic patch that should in theory ostensibly fix this... But may I ask on what kind of file are you trying to apply the `"send current file to Evernote"` operation? As of now I kind of assume people would use it on a markdown or text file (with extensions like '.md', '.markdown', '.txt'), with default note format (in package preference) set to "markdown". I have written some code to handle notes that are in raw html or plain text (so EVND will not perform the markdown->html rendering), but honestly I have not tested those cases (and don't have time to...) so I doubt it actually works.
