### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: b16f325b377ca4e007142741b6527b7b]' of null

### ISSUE THREAD

**Issue by nyuta01** [cs150bf/ever-notedown#33]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.16
### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: b16f325b377ca4e007142741b6527b7b]' of null

```
At /Users/user_name/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: b16f325b377ca4e007142741b6527b7b]' of null
    at NoteIndex.addnote (/Users/user_name/.atom/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/user_name/.atom/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at Object.module.exports.saveNewNote (/Users/user_name/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1384:34)
    at Object.module.exports.file2Evernote (/Users/user_name/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1064:10)
    at /Users/user_name/.atom/packages/ever-notedown/lib/ever-notedown.coffee:475:12
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at HTMLButtonElement.<anonymous> (/Users/user_name/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:453:22)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -0:15.5.0 ever-notedown:new-note (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "ever-notedown": {
    "openNoteInEvernoteAuto": true
  }
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.16
language-haml, v0.23.6
slim-language, v2.2.0

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
What operation were you performing when you see this error? (e.g. were you trying to update a note, click a button, etc.?) Is this problem persistant? (e.g. What happens if you try again after a few seconds?)

I wonder if it has anything to do with the async operation (the json object not having been loaded in time), etc.

**Comment by cs150bf** [comment]
[A solution](https://github.com/cs150bf/ever-notedown/issues/44#issuecomment-171527280) was proposed in a similar issue. Please consider following the preparation steps as described in [the doc](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f) in section `Installation -> Preparation`.

I'll close this issue for now, please let me know if you're still having trouble.
