### ISSUE TITLE
Uncaught TypeError: atom.workspace.open(...).done is not a function

### ISSUE THREAD

**Issue by lukasz-kaniowski** [cs150bf/ever-notedown#34]
Cannot create or pull existing notes.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.16
### Stack Trace

Uncaught TypeError: atom.workspace.open(...).done is not a function

```
At /Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1402

TypeError: atom.workspace.open(...).done is not a function
    at Object.module.exports.openNote (/Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1402:43)
    at /Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1636:12
    at /Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/evernote-helper.coffee:790:29
    at /Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/evernote-helper.coffee:915:24
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```
### Commands

```
     -0:28.2.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
     -0:27 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:27 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:22.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:22.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:21.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.9.0 ever-notedown:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "ever-notedown": {}
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-material-syntax, v0.2.6
atom-material-ui, v0.8.0
atom-typescript, v7.14.1
auto-indent, v0.5.0
ever-notedown, v0.2.16
linter, v1.11.3
linter-ruby, v1.2.0
recent-projects, v0.9.5
sync-settings, v0.6.0
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
I hope 0.2.17 fixes this problem...

**Comment by lukasz-kaniowski** [comment]
Same issue

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.17

### Stack Trace

Uncaught TypeError: atom.workspace.open(...).done is not a function

```
At /Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1402

TypeError: atom.workspace.open(...).done is not a function
    at Object.module.exports.openNote (/Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1402:43)
    at /Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1636:12
    at /Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/evernote-helper.coffee:790:29
    at /Users/lukaszkaniowski/.atom/packages/ever-notedown/lib/evernote-helper.coffee:915:24
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:28.3.0 ever-notedown:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "ever-notedown": {}
}
```

### Installed Packages

``` coffee
# User
.bin, vundefined
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
atom-typescript, v7.14.2
auto-indent, v0.5.0
ever-notedown, v0.2.17
linter, v1.11.3
linter-ruby, v1.2.0
recent-projects, v0.9.5
sync-settings, v0.6.0
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
Have you tried restarting Atom after updating the package? It seems very strange to me that you are still seeing the same error. 

```
Uncaught TypeError: atom.workspace.open(...).done is not a function
```

When I do a search for `done`, it's nowhere to be seen in version 0.2.17.  
&nbsp;

In particular, the line of code indicated in the error log is https://github.com/cs150bf/ever-notedown/blob/4f0d9974989e51d3229451ffaa3d94babafb8553/lib/ever-notedown.coffee#L1402 

```
atom.workspace.open(absPath, options).then (editor) =>
```

Also, I cannot reproduce the error with 0.2.17...

**Comment by lukasz-kaniowski** [comment]
after restarting works like a charm. Thanks!

**Comment by cs150bf** [comment]
Glad to hear that!
