### ISSUE TITLE
Can't save to evernote

### ISSUE THREAD

**Issue by jrekier** [cs150bf/ever-notedown#35]
1. Create new note
2. cmd+s to save 
3. hit the "elephant button" to save to evernote

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.17
### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: 2f840684be31fd1fc61696359d1435f4]' of null

```
At /Users/rekierj/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: 2f840684be31fd1fc61696359d1435f4]' of null
    at NoteIndex.addnote (/Users/rekierj/.atom/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/rekierj/.atom/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at Object.module.exports.saveNewNote (/Users/rekierj/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1384:34)
    at atom-text-editor.window.evnd.newNoteDisposables.(anonymous function).atom.commands.add.core:save (/Users/rekierj/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1332:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -5:02.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:01.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:01.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:00.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:00.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:58.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:50.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.9.0 ever-notedown:import-note-from-evernote (atom-pane.pane.active)
  2x -1:20.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.9.0 core:cancel (atom-pane.pane.active)
     -0:29.7.0 ever-notedown:new-note (atom-pane.pane.active)
  6x -0:23.7.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:20.3.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -0:18.4.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:10.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.17

# Dev
No dev packages
```

**Comment by blimmer** [comment]
Ditto here.
