### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: d6728c2a74e668bbb188e4023b9ee52f]' of null

### ISSUE THREAD

**Issue by GuCarpenter** [cs150bf/ever-notedown#36]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.17
### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: d6728c2a74e668bbb188e4023b9ee52f]' of null

```
At /Users/michael/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: d6728c2a74e668bbb188e4023b9ee52f]' of null
    at NoteIndex.addnote (/Users/michael/.atom/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/michael/.atom/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at Object.module.exports.saveNewNote (/Users/michael/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1384:34)
    at Object.module.exports.file2Evernote (/Users/michael/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1064:10)
    at /Users/michael/.atom/packages/ever-notedown/lib/ever-notedown.coffee:475:12
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at HTMLButtonElement.<anonymous> (/Users/michael/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:454:22)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -0:29.9.0 ever-notedown:new-note (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "ever-notedown": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v1.2.3
ever-notedown, v0.2.17
linter, v1.11.3
linter-flake8, v1.9.2
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
[A solution](https://github.com/cs150bf/ever-notedown/issues/44#issuecomment-171527280) was proposed in a similar issue. Please consider following the preparation steps as described in [the doc](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f) in section `Installation -> Preparation`.

I'll close this issue for now, please let me know if you're still having trouble.
