### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by ajdfajdfl2003** [cs150bf/ever-notedown#40]
**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.17
### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/ajdfajdfl/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:212

TypeError: Cannot read property '0' of null
    at /Users/ajdfajdfl/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:212:45
    at /Users/ajdfajdfl/.atom/packages/ever-notedown/lib/ever-notedown-preview-view.coffee:237:9
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:113:47
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1024:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.restoreScrollTopIfNeeded (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1940:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setLineHeight (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1411:14)
    at LinesComponent.module.exports.LinesComponent.measureLineHeightAndDefaultCharWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-component.js:136:22)
    at TextEditorComponent.module.exports.TextEditorComponent.measureLineHeightAndDefaultCharWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:1002:36)
    at TextEditorComponent.module.exports.TextEditorComponent.sampleFontStyling (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:983:14)
    at TextEditorComponent.sampleFontStyling (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:267:12)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:933:16)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:95:22)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:316:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false
  },
  "ever-notedown": {
    "showPath": false,
    "openNoteInEvernoteAuto": true
  }
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.17

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
~~[A solution](https://github.com/cs150bf/ever-notedown/issues/44#issuecomment-171527280) was proposed in a similar issue. Please consider following the preparation steps as described in [the doc](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f) in section `Installation -> Preparation`.~~

~~I'll close this issue for now, please let me know if you're still having trouble.~~

Oops sorry this issue seems to be different from the others.

**Comment by contextlimit** [comment]
Getting this also

**Comment by anxsec** [comment]
+1

**Comment by jxitc** [comment]
+1
