### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: 06fe24b239671d53792e3e5001d634e3]' of null

### ISSUE THREAD

**Issue by ghost** [cs150bf/ever-notedown#41]
[Enter steps to reproduce below:]
1. Import note from evernote
2. Search for Query String

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.17
### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: 06fe24b239671d53792e3e5001d634e3]' of null

```
At /Users/chrisbamborough/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: 06fe24b239671d53792e3e5001d634e3]' of null
    at NoteIndex.addnote (/Users/chrisbamborough/.atom/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/chrisbamborough/.atom/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at /Users/chrisbamborough/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1611:38
    at /Users/chrisbamborough/.atom/packages/ever-notedown/lib/evernote-helper.coffee:1056:9
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -3:17.1.0 ever-notedown:toggle-preview (atom-text-editor.editor.is-focused)
  4x -2:27.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:08.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "ever-notedown": {
    "openNoteInEvernoteAuto": true,
    "pulledContentInSplitPane": true
  }
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.17
highlight-line, v0.11.0
rhino-python, v0.8.0
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
[A solution](https://github.com/cs150bf/ever-notedown/issues/44#issuecomment-171527280) was proposed in a similar issue. Please consider following the preparation steps as described in [the doc](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f) in section `Installation -> Preparation`.

I'll close this issue for now, please let me know if you're still having trouble.
