### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: f8c936067e9595e2d19cafc019a629fd]' of null

### ISSUE THREAD

**Issue by qinf** [cs150bf/ever-notedown#44]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.10.4
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.18
### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: f8c936067e9595e2d19cafc019a629fd]' of null

```
At /Users/qinf/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: f8c936067e9595e2d19cafc019a629fd]' of null
    at NoteIndex.addnote (/Users/qinf/.atom/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/qinf/.atom/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at /Users/qinf/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1611:38
    at /Users/qinf/.atom/packages/ever-notedown/lib/evernote-helper.coffee:1056:9
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -5:57 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -5:20.5.0 ever-notedown:open-config (div.pane-item.native-key-bindings.about)
     -5:05.2.0 ever-notedown:toggle (div.pane-item.native-key-bindings.about)
     -4:43.4.0 ever-notedown:import-note-from-evernote (div.pane-item.native-key-bindings.about)
     -3:21 ever-notedown:new-note (div.pane-item.native-key-bindings.about)
  2x -3:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:59.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:55 core:save (atom-text-editor.editor.is-focused)
  2x -1:05.4.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close.has-stack)
     -0:12.1.0 ever-notedown:import-note-from-evernote (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.18
ever-notedown, v0.2.18

# Dev
No dev packages
```

**Comment by qinf** [comment]
`echo "{}" > index.json` can deal with this issue!
For more information, please go to visite [Install ever-notedown](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f?content=#toc:install)

If you can't open the link above, you can try this [EVND (Ever Notedown) Demo - Help Document (Draft)](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f). `Installation -> Preparation` part will give you some help!
Thanks  @cs150bf !

**Comment by cs150bf** [comment]
@qinf Thanks for the feedback!

And for those of you reading this post and having trouble opening the link, try [this](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f) and click `Installation -> Preparation` from the Table of Contents
