### ISSUE TITLE
Uncaught TypeError: Cannot read property 'jsonOBJ' of null

### ISSUE THREAD

**Issue by DemisR** [cs150bf/ever-notedown#49]
1. From packages menu open  : Toggle NoteList

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.3
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.18
### Stack Trace

Uncaught TypeError: Cannot read property 'jsonOBJ' of null

```
At /Users/deri/.atom/packages/ever-notedown/lib/note-manager-view.coffee:95

TypeError: Cannot read property 'jsonOBJ' of null
    at NoteManagerView.module.exports.NoteManagerView.show (/Users/deri/.atom/packages/ever-notedown/lib/note-manager-view.coffee:95:41)
    at NoteManagerView.module.exports.NoteManagerView.toggle (/Users/deri/.atom/packages/ever-notedown/lib/note-manager-view.coffee:86:8)
    at atom-workspace.subscriptions.add.atom.commands.add.ever-notedown:toggle-note-list (/Users/deri/.atom/packages/ever-notedown/lib/ever-notedown.coffee:360:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:01.3.0 ever-notedown:toggle-note-list (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tree-view-finder",
      "save-session",
      "linter-pylama",
      "linter-shellcheck",
      "linter"
    ]
  },
  "ever-notedown": {}
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.18
file-icons, v1.6.14
git-log, v0.4.1
language-generic-config, v1.0.0
language-nagios, v0.2.0
open-recent, v4.0.1

# Dev
No dev packages
```

**Comment by 7k50** [comment]
The issue seems to be that `index.json` in your `envd` folder has been nulled to 0 bytes. The file indexes all your notes and note meta data. It happens from time to time, that the file is emptied for reasons that are unknown to me.

Luckily I keep my EVND notes in a symlinked Dropbox folder, so I'm able to restore the latest usable version. You should thus backup your `index.json` file. After replacing the 0 byte file, restart Atom and try again.
