### ISSUE TITLE
Uncaught TypeError: this.searchedOpenedNote is not a function

### ISSUE THREAD

**Issue by mvattuone** [cs150bf/ever-notedown#51]
When I try to pull the current note from Evernote using the option available via Shift+Cmd+P, I receive an error. Let me know if you need more info on this.

**Atom Version**: 1.4.2
**System**: Mac OS X 10.10.5
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.18
### Stack Trace

Uncaught TypeError: this.searchedOpenedNote is not a function

```
At /Users/mvattuon/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1626

TypeError: this.searchedOpenedNote is not a function
    at Object.module.exports.pullFromEvernote (/Users/mvattuon/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1626:15)
    at atom-workspace.<anonymous> (/Users/mvattuon/.atom/packages/ever-notedown/lib/ever-notedown.coffee:369:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:56.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:56.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  7x -0:54.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:47.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:11.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:09.5.0 symbols-view:toggle-project-symbols (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:07.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.6.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  4x -0:04.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -0:02.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 ever-notedown:pull-current-note-from-evernote (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {},
  "ever-notedown": {}
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.18

# Dev
No dev packages
```

**Comment by MissingRoberto** [comment]
Same issue here...
