### ISSUE TITLE
it would not install

### ISSUE THREAD

**Issue by rmchale** [cs150bf/ever-notedown#58]
```
> git-utils@4.1.2 install /private/var/folders/_p/dv2mcjjj3_5g15bw3ggwycqr0000gn/T/apm-install-dir-116220-57212-cs7akx/node_modules/ever-notedown/node_modules/git-utils
> node-gyp rebuild

  CC(target) Release/obj.target/libgit2/deps/libgit2/src/annotated_commit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attr.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attr_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attrcache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blame.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blame_git.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blob.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/branch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/buf_text.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/buffer.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/checkout.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/cherrypick.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/clone.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/commit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/commit_list.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config_cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/crlf.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/curl_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/date.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/delta-apply.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/delta.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/describe.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_driver.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_patch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_print.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_stats.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_tform.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_xdiff.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/errors.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fetch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fetchhead.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/filebuf.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fileops.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/filter.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fnmatch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/global.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/graph.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hash.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hashsig.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/ident.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/ignore.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/index.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/indexer.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/iterator.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/merge.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/merge_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/message.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/mwindow.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/netops.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/notes.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/object.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/object_api.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_loose.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_mempack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_pack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/oid.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/oidarray.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/openssl_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pack-objects.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/path.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pathspec.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pool.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/posix.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pqueue.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/push.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/rebase.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refdb.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refdb_fs.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/reflog.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refs.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refspec.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/remote.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/repository.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/reset.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revert.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revparse.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revwalk.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/settings.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sha1_lookup.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/signature.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/socket_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sortedcache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/stash.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/status.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/stransport_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/strmap.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/submodule.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sysdir.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tag.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/thread-utils.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tls_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/trace.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transaction.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transport.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tree-cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tree.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tsort.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/util.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/vector.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/zstream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/auth.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/auth_negotiate.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/cred.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/cred_helpers.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/git.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/http.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/local.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart_pkt.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart_protocol.o

  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/ssh.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/winhttp.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xdiffi.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xemit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xhistogram.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xmerge.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xpatience.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xprepare.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xutils.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hash/hash_generic.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/unix/map.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/unix/realpath.o
  LIBTOOL-STATIC Release/git2.a
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/adler32.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/crc32.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/deflate.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/inffast.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/inflate.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/trees.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/zutil.o
  LIBTOOL-STATIC Release/zlib.a
  CC(target) Release/obj.target/http_parser/deps/libgit2/deps/http-parser/http_parser.o
  LIBTOOL-STATIC Release/http_parser.a
  CXX(target) Release/obj.target/git/src/repository.o

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
../node_modules/nan/nan.h:410:16: error: no matching constructor for initialization of 'v8::TryCatch'
  TryCatch() : try_catch_(v8::Isolate::GetCurrent()) {}
               ^          ~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rmchale/.atom/.node-gyp/.node-gyp/0.20.0/deps/v8/include/v8.h:5371:3: note: candidate constructor not viable: no known conversion from 'v8::Isolate *' to 'const v8::TryCatch' for 1st argument
  TryCatch(const TryCatch&);
  ^
/Users/rmchale/.atom/.node-gyp/.node-gyp/0.20.0/deps/v8/include/v8.h:5254:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  TryCatch();
  ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
../node_modules/nan/nan.h:2029:8: error: no member named 'SetHandler' in 'v8::ObjectTemplate'
  tpl->SetHandler(v8::NamedPropertyHandlerConfiguration(
  ~~~  ^
../node_modules/nan/nan.h:2029:23: error: no member named 'NamedPropertyHandlerConfiguration' in namespace 'v8'
  tpl->SetHandler(v8::NamedPropertyHandlerConfiguration(
                  ~~~~^
../node_modules/nan/nan.h:2099:8: error: no member named 'SetHandler' in 'v8::ObjectTemplate'
  tpl->SetHandler(v8::IndexedPropertyHandlerConfiguration(
  ~~~  ^
../node_modules/nan/nan.h:2099:23: error: no member named 'IndexedPropertyHandlerConfiguration' in namespace 'v8'
  tpl->SetHandler(v8::IndexedPropertyHandlerConfiguration(
                  ~~~~^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
In file included from ../node_modules/nan/nan.h:2157:
../node_modules/nan/nan_weak.h:93:31: error: no template named 'PhantomCallbackData' in namespace 'v8'; did you mean 'WeakCallbackData'?
  static void invokeparameter(NAN_WEAK_PARAMETER_CALLBACK_SIG_ data);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:35:43: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_SIG_'
# define NAN_WEAK_PARAMETER_CALLBACK_SIG_ NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:32:9: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_'
    v8::PhantomCallbackData<WeakCallbackInfo<T> > const&
    ~~~~^
/Users/rmchale/.atom/.node-gyp/.node-gyp/0.20.0/deps/v8/include/v8.h:417:7: note: 'WeakCallbackData' declared here
class WeakCallbackData {
      ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
In file included from ../node_modules/nan/nan.h:2157:
../node_modules/nan/nan_weak.h:93:31: error: too few template arguments for class template 'WeakCallbackData'
  static void invokeparameter(NAN_WEAK_PARAMETER_CALLBACK_SIG_ data);
                              ^
../node_modules/nan/nan_weak.h:35:43: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_SIG_'
# define NAN_WEAK_PARAMETER_CALLBACK_SIG_ NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_
                                          ^
../node_modules/nan/nan_weak.h:32:9: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_'
    v8::PhantomCallbackData<WeakCallbackInfo<T> > const&
        ^
/Users/rmchale/.atom/.node-gyp/.node-gyp/0.20.0/deps/v8/include/v8.h:417:7: note: template is declared here
class WeakCallbackData {
      ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
In file included from ../node_modules/nan/nan.h:2157:
../node_modules/nan/nan_weak.h:94:30: error: no type named 'InternalFieldsCallbackData' in namespace 'v8'
  static void invoketwofield(NAN_WEAK_TWOFIELD_CALLBACK_SIG_ data);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:36:42: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_SIG_'
# define NAN_WEAK_TWOFIELD_CALLBACK_SIG_ NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:34:9: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_'
    v8::InternalFieldsCallbackData<WeakCallbackInfo<T>, void> const&
    ~~~~^
../node_modules/nan/nan_weak.h:94:30: error: expected ')'
../node_modules/nan/nan_weak.h:36:42: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_SIG_'
# define NAN_WEAK_TWOFIELD_CALLBACK_SIG_ NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_
                                         ^
../node_modules/nan/nan_weak.h:34:35: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_'
    v8::InternalFieldsCallbackData<WeakCallbackInfo<T>, void> const&
                                  ^
../node_modules/nan/nan_weak.h:94:29: note: to match this '('
  static void invoketwofield(NAN_WEAK_TWOFIELD_CALLBACK_SIG_ data);
                            ^
../node_modules/nan/nan_weak.h:96:7: error: no template named 'PhantomCallbackData' in namespace 'v8'; did you mean 'WeakCallbackData'?
      NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_ data);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:32:9: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_'
    v8::PhantomCallbackData<WeakCallbackInfo<T> > const&
    ~~~~^
/Users/rmchale/.atom/.node-gyp/.node-gyp/0.20.0/deps/v8/include/v8.h:417:7: note: 'WeakCallbackData' declared here
class WeakCallbackData {
      ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
In file included from ../node_modules/nan/nan.h:2157:
../node_modules/nan/nan_weak.h:96:7: error: too few template arguments for class template 'WeakCallbackData'
      NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_ data);
      ^
../node_modules/nan/nan_weak.h:32:9: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_'
    v8::PhantomCallbackData<WeakCallbackInfo<T> > const&
        ^
/Users/rmchale/.atom/.node-gyp/.node-gyp/0.20.0/deps/v8/include/v8.h:417:7: note: template is declared here
class WeakCallbackData {
      ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
In file included from ../node_modules/nan/nan.h:2157:
../node_modules/nan/nan_weak.h:98:7: error: no type named 'InternalFieldsCallbackData' in namespace 'v8'
      NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_ data);

      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:34:9: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_'
    v8::InternalFieldsCallbackData<WeakCallbackInfo<T>, void> const&
    ~~~~^
../node_modules/nan/nan_weak.h:98:7: error: expected ')'
../node_modules/nan/nan_weak.h:34:35: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_'
    v8::InternalFieldsCallbackData<WeakCallbackInfo<T>, void> const&
                                  ^
../node_modules/nan/nan_weak.h:97:42: note: to match this '('
  static WeakCallbackInfo *unwraptwofield(
                                         ^
../node_modules/nan/nan_weak.h:158:38: error: no template named 'PhantomCallbackData' in namespace 'v8'; did you mean 'WeakCallbackData'?
WeakCallbackInfo<T>::invokeparameter(NAN_WEAK_PARAMETER_CALLBACK_SIG_ data) {
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:35:43: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_SIG_'
# define NAN_WEAK_PARAMETER_CALLBACK_SIG_ NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:32:9: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_'
    v8::PhantomCallbackData<WeakCallbackInfo<T> > const&
    ~~~~^
/Users/rmchale/.atom/.node-gyp/.node-gyp/0.20.0/deps/v8/include/v8.h:417:7: note: 'WeakCallbackData' declared here
class WeakCallbackData {
      ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
In file included from ../node_modules/nan/nan.h:2157:
../node_modules/nan/nan_weak.h:158:38: error: too few template arguments for class template 'WeakCallbackData'
WeakCallbackInfo<T>::invokeparameter(NAN_WEAK_PARAMETER_CALLBACK_SIG_ data) {
                                     ^
../node_modules/nan/nan_weak.h:35:43: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_SIG_'
# define NAN_WEAK_PARAMETER_CALLBACK_SIG_ NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_
                                          ^
../node_modules/nan/nan_weak.h:32:9: note: expanded from macro 'NAN_WEAK_PARAMETER_CALLBACK_DATA_TYPE_'
    v8::PhantomCallbackData<WeakCallbackInfo<T> > const&
        ^
/Users/rmchale/.atom/.node-gyp/.node-gyp/0.20.0/deps/v8/include/v8.h:417:7: note: template is declared here
class WeakCallbackData {
      ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
In file included from ../node_modules/nan/nan.h:2157:
../node_modules/nan/nan_weak.h:167:22: error: variable has incomplete type 'void'
WeakCallbackInfo<T>::invoketwofield(NAN_WEAK_TWOFIELD_CALLBACK_SIG_ data) {
                     ^
../node_modules/nan/nan_weak.h:167:37: error: no member named 'InternalFieldsCallbackData' in namespace 'v8'
WeakCallbackInfo<T>::invoketwofield(NAN_WEAK_TWOFIELD_CALLBACK_SIG_ data) {
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:36:42: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_SIG_'
# define NAN_WEAK_TWOFIELD_CALLBACK_SIG_ NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:34:9: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_'
    v8::InternalFieldsCallbackData<WeakCallbackInfo<T>, void> const&
    ~~~~^
../node_modules/nan/nan_weak.h:167:37: error: expected '(' for function-style cast or type construction
WeakCallbackInfo<T>::invoketwofield(NAN_WEAK_TWOFIELD_CALLBACK_SIG_ data) {
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:36:42: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_SIG_'
# define NAN_WEAK_TWOFIELD_CALLBACK_SIG_ NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:34:55: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_'
    v8::InternalFieldsCallbackData<WeakCallbackInfo<T>, void> const&
                                   ~~~~~~~~~~~~~~~~~~~^
../node_modules/nan/nan_weak.h:167:37: error: expected '(' for function-style cast or type construction
WeakCallbackInfo<T>::invoketwofield(NAN_WEAK_TWOFIELD_CALLBACK_SIG_ data) {
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:36:42: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_SIG_'
# define NAN_WEAK_TWOFIELD_CALLBACK_SIG_ NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_weak.h:34:61: note: expanded from macro 'NAN_WEAK_TWOFIELD_CALLBACK_DATA_TYPE_'
    v8::InternalFieldsCallbackData<WeakCallbackInfo<T>, void> const&
                                                        ~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/git/src/repository.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/_p/dv2mcjjj3_5g15bw3ggwycqr0000gn/T/apm-install-dir-116220-57212-cs7akx/node_modules/ever-notedown/node_modules/git-utils
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/.apmrc" "--userconfig" "/Users/rmchale/.atom/.apmrc" "install" "/private/var/folders/_p/dv2mcjjj3_5g15bw3ggwycqr0000gn/T/d-116220-57212-rzpph7/package.tgz" "--target=0.20.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/_p/dv2mcjjj3_5g15bw3ggwycqr0000gn/T/apm-install-dir-116220-57212-cs7akx/npm-debug.log
```

**Comment by geeknees** [comment]
please check this! It might help.
https://github.com/cs150bf/ever-notedown/issues/75

**Comment by cs150bf** [comment]
I think this issue is the same as https://github.com/cs150bf/ever-notedown/issues/82 so I'll close this one for now. Please let me know if you don't think it's a duplicate.
