### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: f6fb907647d119ea1bed0f101cf6eb54]' of null

### ISSUE THREAD

**Issue by ghost** [cs150bf/ever-notedown#61]
I get this error when trying to open a note after entering the note link. (I'm using Evernote 6.6 beta 3)

**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.4
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.18
### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: f6fb907647d119ea1bed0f101cf6eb54]' of null

```
At /Users/ucac005/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: f6fb907647d119ea1bed0f101cf6eb54]' of null
    at NoteIndex.addnote (/Users/ucac005/.atom/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/ucac005/.atom/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at /Users/ucac005/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1611:38
    at /Users/ucac005/.atom/packages/ever-notedown/lib/evernote-helper.coffee:1056:9
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -3:49.4.0 ever-notedown:toggle (div.pane-item.native-key-bindings.about)
  2x -3:44.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:56.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:05.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:10.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:10.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "ever-notedown": {}
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.18
markdown-preview-plus, v2.3.0
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by ghost** [comment]
Problem persists with version 6.6.
