### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: 4d9898165cfcda4843654ad55eb0c1b6]' of null

### ISSUE THREAD

**Issue by yxy** [cs150bf/ever-notedown#62]
[Enter steps to reproduce below:]

when I try to save the note, bad things happened :(

any ideas?

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.2
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.18
### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: 4d9898165cfcda4843654ad55eb0c1b6]' of null

```
At /Users/yxy/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: 4d9898165cfcda4843654ad55eb0c1b6]' of null
  at NoteIndex.addnote (/Users/yxy/.atom/packages/ever-notedown/lib/note-helper.coffee:95:5)
  at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/yxy/.atom/packages/ever-notedown/lib/storage-manager.coffee:197:27)
  at Object.module.exports.saveNewNote (/Users/yxy/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1384:34)
  at atom-text-editor.window.evnd.newNoteDisposables.(anonymous function).atom.commands.add.core:save (/Users/yxy/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1332:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```
### Commands

```
     -0:22.2.0 ever-notedown:new-note (atom-pane.pane.active)
     -0:19.7.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:19.1.0 vim-mode:move-to-start-of-file (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:19 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:18.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:18.4.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:16.9.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:16.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:15.9.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:15.2.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:14.8.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:12.9.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:10.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:10.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.6.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:08.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "ever-notedown": {}
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.18
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.17.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.129.0
tool-bar, v0.4.0
vim-mode, v0.65.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by yxy** [comment]
It's weird.

I try to solve this issue.

I cd the evnd directory which is ~/.atom/evnd, I removed all the files except the`.git` directory, and put `{}` into the index.js file. Then I try to open atom create a new evnd, save to Evernote, everything works fine.
