### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: d1f3c28bb993c8b287abc1dffed20ed0]' of null

### ISSUE THREAD

**Issue by reven404** [cs150bf/ever-notedown#66]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.18
### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: d1f3c28bb993c8b287abc1dffed20ed0]' of null

```
At /Users/Reven/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: d1f3c28bb993c8b287abc1dffed20ed0]' of null
    at NoteIndex.addnote (/Users/Reven/.atom/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/Users/Reven/.atom/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at Object.module.exports.saveNewNote (/Users/Reven/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1384:34)
    at atom-text-editor.window.evnd.newNoteDisposables.(anonymous function).atom.commands.add.core:save (/Users/Reven/.atom/packages/ever-notedown/lib/ever-notedown.coffee:1332:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
 16x -2:17.7.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
 21x -2:16.9.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
 20x -2:15.4.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:14.3.0 vim-mode-plus:move-to-last-line (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -2:13.9.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
 14x -2:13.4.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:12.5.0 vim-mode-plus:move-to-first-line (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
 24x -2:12.2.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
 23x -2:10.8.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  3x -2:09.2.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  4x -1:59.8.0 markdown-preview:toggle (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -1:49.8.0 ever-notedown:toggle-preview (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:15.7.0 core:close (select#ever-notedown.noteTemplate.form-control)
  3x -0:14.8.0 core:save (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:04.4.0 tree-view:remove (div.header.list-item)
     -0:01.7.0 core:save (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "language-perl"
    ]
  },
  "ever-notedown": {
    "breakOnSingleNewline": true,
    "gitPath": "/Users/Reven/Documents/Projects/FitzHelp/doc/documents",
    "pulledContentInSplitPane": true,
    "smartyPants": true,
    "theme": "Atom"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.5.2
autocomplete-ctags, v0.4.1
autocomplete-python, v1.7.2
build, v0.61.0
ever-notedown, v0.2.18
go-config, v1.1.4
go-get, v1.0.3
go-hyperclick, v1.1.0
hyperclick, v0.0.36
js-hyperclick, v1.4.2
language-perl6fe, v1.7.1
linter, v1.11.4
navigator-godef, v1.0.3
pigments, v0.26.0
react, v0.15.0
refactor, v0.6.0
slickedit-select, v1.6.0
vim-mode-plus, v0.38.0

# Dev
No dev packages
```

**Comment by schallerala** [comment]
- 1

I installed the package in Atom, and when I toggle the panel, the list of Notebook is empty. I can search through my notes with the search function but when I try to open them, I got the same kind of error than when I try to create a note and export it to Evernote.
