### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 47, got 14.

### ISSUE THREAD

**Issue by outofmemoryerror** [cs150bf/ever-notedown#67]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.3
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package, v0.2.18
### Stack Trace

Uncaught Error: Module version mismatch. Expected 47, got 14.

```
At ATOM_SHELL_ASAR.js:159

Error: Module version mismatch. Expected 47, got 14.
    at Error (native)
    at process.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alex/.atom/packages/ever-notedown/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/Users/alex/.atom/packages/ever-notedown/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.loadModule (/Users/alex/.atom/packages/ever-notedown/lib/ever-notedown.coffee:2059:12)
    at Object.module.exports.showImportNotePanel (/Users/alex/.atom/packages/ever-notedown/lib/ever-notedown.coffee:878:31)
    at atom-workspace.<anonymous> (/Users/alex/.atom/packages/ever-notedown/lib/ever-notedown.coffee:372:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:26.9.0 ever-notedown:new-note (ul.list-inline.tab-bar.inset-panel)
     -0:00.6.0 ever-notedown:import-note-from-evernote (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "bookmarks",
      "markdown-preview",
      "autosave-plus",
      "autosave-plus",
      "autosave-plus"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
ever-notedown, v0.2.18
markdown-preview-plus, v2.4.0
markdown-scroll-sync, v2.1.2
vim-mode-plus, v0.32.1

# Dev
No dev packages
```

**Comment by cs150bf** [comment]
This looks like the same problem as https://github.com/cs150bf/ever-notedown/issues/83. Please refer to that one for now.  Or let me know if you think these two are actually separate ones.
