### ISSUE TITLE
Failed to install in Atom 

### ISSUE THREAD

**Issue by hackjutsu** [cs150bf/ever-notedown#75]
```
Installing “ever-notedown@0.2.24” failed.Hide output…

> git-utils@4.1.2 install /private/var/folders/dm/8w4ngq6s4_1dbp2mf318n5880000gp/T/apm-install-dir-11679-20181-wixc85/node_modules/ever-notedown/node_modules/git-utils
> node-gyp rebuild

  CC(target) Release/obj.target/libgit2/deps/libgit2/src/annotated_commit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attr.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attr_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attrcache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blame.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blame_git.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blob.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/branch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/buf_text.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/buffer.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/checkout.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/cherrypick.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/clone.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/commit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/commit_list.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config_cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/crlf.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/curl_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/date.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/delta-apply.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/delta.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/describe.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_driver.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_patch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_print.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_stats.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_tform.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_xdiff.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/errors.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fetch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fetchhead.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/filebuf.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fileops.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/filter.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fnmatch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/global.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/graph.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hash.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hashsig.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/ident.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/ignore.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/index.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/indexer.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/iterator.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/merge.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/merge_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/message.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/mwindow.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/netops.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/notes.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/object.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/object_api.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_loose.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_mempack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_pack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/oid.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/oidarray.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/openssl_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pack-objects.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/path.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pathspec.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pool.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/posix.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pqueue.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/push.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/rebase.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refdb.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refdb_fs.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/reflog.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refs.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refspec.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/remote.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/repository.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/reset.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revert.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revparse.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revwalk.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/settings.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sha1_lookup.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/signature.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/socket_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sortedcache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/stash.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/status.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/stransport_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/strmap.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/submodule.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sysdir.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tag.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/thread-utils.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tls_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/trace.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transaction.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transport.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tree-cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tree.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tsort.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/util.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/vector.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/zstream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/auth.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/auth_negotiate.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/cred.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/cred_helpers.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/git.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/http.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/local.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart_pkt.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart_protocol.o

  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/ssh.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/winhttp.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xdiffi.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xemit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xhistogram.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xmerge.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xpatience.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xprepare.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xutils.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hash/hash_generic.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/unix/map.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/unix/realpath.o
  LIBTOOL-STATIC Release/git2.a

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/git2.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/dm/8w4ngq6s4_1dbp2mf318n5880000gp/T/apm-install-dir-11679-20181-wixc85/node_modules/ever-notedown/node_modules/git-utils
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/<My username>/.atom/.apm/.apmrc" "--userconfig" "/Users/<My username>/.atom/.apmrc" "install" "/private/var/folders/dm/8w4ngq6s4_1dbp2mf318n5880000gp/T/d-11679-20181-10moy74/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/dm/8w4ngq6s4_1dbp2mf318n5880000gp/T/apm-install-dir-11679-20181-wixc85/npm-debug.log

```

**Comment by 7Moses** [comment]
Me too, no success with this update. I also tried this guidance, https://github.com/cs150bf/ever-notedown/issues/22, see my ID, and again no success with the update,

**Comment by rollonbears234** [comment]
+1

**Comment by geeknees** [comment]
I have the same problem. I changed python version from 3.5 to 2.7, then succeeded. It might help.

**Comment by cs150bf** [comment]
Another thing that you might want to try is to remove the previously built `git-utils` before rebuilding the package:

```bash
> cd ~/.atom/packages/ever-notedown/node_modules
> npm remove git-utils
> cd ..
> apm rebuild
```

It worked for me. 

Also thank you @mgka for the advice! I haven't tried it myself yet but I see there are reports of success (https://github.com/cs150bf/ever-notedown/issues/82).

**Comment by cs150bf** [comment]
As this looks like the same issue as https://github.com/cs150bf/ever-notedown/issues/82, I'll close this one for now. If that's a mistake please let me know.
