### ISSUE TITLE
Receiving the following error when using app install ever-notedown

### ISSUE THREAD

**Issue by rollonbears234** [cs150bf/ever-notedown#82]
It isn't working installing through the Atom editor either

> git-utils@4.1.2 install /private/var/folders/lp/ck9rg1ys3_158kb1572kzhf80000gn/T/apm-install-dir-116105-35636-13qawm6/node_modules/ever-notedown/node_modules/git-utils
> node-gyp rebuild

/private/var/folders/lp/ck9rg1ys3_158kb1572kzhf80000gn/T/apm-install-dir-116105-35636-13qawm6
└── (empty)

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
make: *** No rule to make target `../../../../../../../../../../../../Applications/Text', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Text Editors /Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Applications/Text Editors /Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Text Editors /Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/lp/ck9rg1ys3_158kb1572kzhf80000gn/T/apm-install-dir-116105-35636-13qawm6/node_modules/ever-notedown/node_modules/git-utils
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/lp/ck9rg1ys3_158kb1572kzhf80000gn/T/apm-install-dir-116105-35636-13qawm6/package.json'
npm WARN apm-install-dir-116105-35636-13qawm6 No description
npm WARN apm-install-dir-116105-35636-13qawm6 No repository field.
npm WARN apm-install-dir-116105-35636-13qawm6 No README data
npm WARN apm-install-dir-116105-35636-13qawm6 No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Text Editors /Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Text Editors /Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/bryanalcorn/.atom/.apm/.apmrc" "--userconfig" "/Users/bryanalcorn/.atom/.apmrc" "install" "/private/var/folders/lp/ck9rg1ys3_158kb1572kzhf80000gn/T/d-116105-35636-1jsc6w8/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! git-utils@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-utils@4.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs git-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/lp/ck9rg1ys3_158kb1572kzhf80000gn/T/apm-install-dir-116105-35636-13qawm6/npm-debug.log
npm ERR! code 1

**Comment by geeknees** [comment]
Please check this! It might help.
https://github.com/cs150bf/ever-notedown/issues/75

**Comment by RabbitLee** [comment]
@mgka 
Hello~ I used python2 (/usr/bin/python), but still got that error above. How do you mean by "changed python version from 3.5 to 2.7"?
PS: When I input 'python' in terminal, I got the python 2.7.10 environment.

**Comment by geeknees** [comment]
@RabbitLee 
Hi! I I suspected that this is a compatibility problem between python3 and git-util. 

https://github.com/atom/git-utils/issues/72#issuecomment-263755735

**Comment by RabbitLee** [comment]
@mgka 
Finally, I made it!

I have downloaded the zip file of ever-notedown, use 
```bash
npm config set python /path/to/executable/python2.7
npm install
```
to install, but still get the failure
```python
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
```
I even used an alias to ensure my python version
```bash
alias python="usr/bin/python2.7"
```

At last, I changed the ~/.bash_profile, deleting anaconda python and it worked.
Thank you !

**Comment by cs150bf** [comment]
Another thing that you might want to try is to remove the previously built `git-utils` before rebuilding the package:

```bash
> cd ~/.atom/packages/ever-notedown/node_modules
> npm remove git-utils
> cd ..
> apm rebuild
```

It worked for me. 

Also thank you @mgka for the advice! I haven't tried it myself yet but I see there are reports of success (https://github.com/cs150bf/ever-notedown/issues/82).

**Comment by cs150bf** [comment]
Potential duplicates: 
- https://github.com/cs150bf/ever-notedown/issues/75
- https://github.com/cs150bf/ever-notedown/issues/58
