### ISSUE TITLE
Uncaught TypeError: Cannot set property '[Note ID: 468f27f0ac9142eef611809e437ede30]' of null

### ISSUE THREAD

**Issue by svenwei** [cs150bf/ever-notedown#94]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [ever-notedown](https://github.com/cs150bf/ever-notedown) package 0.2.27

### Stack Trace

Uncaught TypeError: Cannot set property '[Note ID: 468f27f0ac9142eef611809e437ede30]' of null

```
At /Users/hadoob/.atom/packages/ever-notedown/lib/note-helper.coffee:95

TypeError: Cannot set property '[Note ID: 468f27f0ac9142eef611809e437ede30]' of null
    at NoteIndex.addnote (/packages/ever-notedown/lib/note-helper.coffee:95:5)
    at StorageManager.exports.StorageManager.StorageManager.addNote (/packages/ever-notedown/lib/storage-manager.coffee:197:27)
    at Object.saveNewNote (/packages/ever-notedown/lib/ever-notedown.coffee:1384:34)
    at Object.file2Evernote (/packages/ever-notedown/lib/ever-notedown.coffee:1064:10)
    at /packages/ever-notedown/lib/ever-notedown.coffee:475:12
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /packages/ever-notedown/lib/ever-notedown-preview-view.coffee:454:22)
    at HTMLButtonElement.dispatch (/packages/ever-notedown/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/ever-notedown/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:55.5.0 ever-notedown:import-note-from-evernote (atom-pane.pane.active)
     -4:32.8.0 ever-notedown:toggle-note-list (atom-pane.pane.active)
     -4:27.2.0 core:confirm (input.hidden-input)
     -4:16.4.0 ever-notedown:open-config (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:45.5.0 ever-notedown:edit-macros-custom2 (input.hidden-input)
  2x -2:46.9.0 ever-notedown:toggle (input.hidden-input)
     -1:36.4.0 ever-notedown:import-note-from-evernote (button.btn.btn-default.icon.icon-link)
     -1:27 core:close (input.hidden-input)
     -1:15.3.0 ever-notedown:selection-to-evernote (atom-pane.pane.active)
     -1:07.3.0 ever-notedown:new-note (atom-pane.pane.active)
```

### Non-Core Packages

```
ever-notedown 0.2.27 
```

**Comment by dpinezich** [comment]
Jep same here :(

**Comment by 109km** [comment]
same

**Comment by lucifer-heaven** [comment]
same

**Comment by lucifer-heaven** [comment]
Oh I made it!! I just read help document again, and edited the grammars in the preferences.  then it works!
